name: Backend CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ⚙️ Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Change this if you're using .NET 7 or another version

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🛠️ Build the project
        run: dotnet build --no-restore --configuration Release