name: Conventional Commits

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Validate commit message format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            chore
            refactor
            test
            hotfix
            ci
            exp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}